Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/deploy/urls.py
#coding:utf-8
from django.conf.urls import url
from .views import  *
from .views_key import *

urlpatterns = [
    url(r'^key_list/',salt_key_list,name='key_list'),
    url(r'^key_delete/',salt_delete_key,name='key_delete'),
    url(r'^key_accept/',salt_accept_key,name='accept_key'),
    url(r'^module_deploy/',module_deploy,name='module_deploy'),
    url(r'^module_fabu/',module_fabu,name='module_fabu'),
    url(r'^remote_execution/',remote_execution,name='remote_execution'),
    url(r'^code_deploy/',code_deploy,name='code_deploy'),
    url(r'^change_ver/',change_ver,name='change_ver'),

]

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/oms/urls.py
#coding:utf-8
from django.conf.urls import url,include
from django.contrib import admin
from . import  views

urlpatterns = [
    url(r'^oms/admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^deploy/',include('deploy.urls', namespace="deploy")),
    url(r'^asset/',include('asset.urls', namespace="asset")),
    url(r'^installed/',include('installed.urls', namespace="installed")),
    url(r'^monitor/',include('monitor.urls', namespace="monitor")),
    url(r'^content/',include('content.urls', namespace="content")),
    url(r'^user/',include('user_center.urls', namespace="user")),

]

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/change_ver.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">添加或者修改git版本</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">新增模块请联系管理员</h1>
            </div>
       </div>

{#{{ error }}接收后台返回的错误信息封装在ul，li标签里面：#}
    {{ error }}


       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                             <form class="form-horizontal form-border" method="post" enctype="multipart/form-data" action="">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">模块</label>

                                        <div class="col-sm-6">
                                             <select name="module">
                                                  {% for mod in module %}
                                            <option value="{{ mod }}">{{ mod }}</option>
                                                  {% endfor %}
                                             </select>

                                        </div>
                                    </div>

                                 <div class="form-group">
                                        <label class="col-sm-3 control-label">分支版本</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="ver" value="">
                                        </div>
                                    </div>

                                 <div class="form-group">
                                        <label class="col-sm-3 control-label">编译环境</label>
                                        <div class="col-sm-6">
                                            <select name="env">
                                                <option value="pre">pre</option>
                                                <option value="prod">prod</option>
                                                </select>
                                        </div>
                                    </div>

                                 <div class="col-sm-offset-8 col-sm-10" >
                                     <button type="submit" class="btn btn-primary" >修改分支</button>

                                     </div>





                             </form>
                      </div>
                 </div>
            </div>
       </div>
       <!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/code_deploy.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block css %}
<!-- iCheck-->
<link rel="stylesheet" href="assets/plugins/icheck/css/_all.css">
{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">代码发布</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">代码发布</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                             <form class="form-horizontal form-border" method="post" enctype="multipart/form-data" action="/deploy/code_deploy/?action=push">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">项目</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="project" value={{ project }}>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">代码url</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="url" value={{ url }}>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">版本号</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="version" value={{ version }}>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">部署环境</label>
                                        <div class="col-sm-6">
                                            <label class="radio-inline">
                                                <input class="icheck" type="radio" checked="" name="env" value="beta">测试</label>
                                            <label class="radio-inline">
                                                <input class="icheck" type="radio" name="env" value="ga">正式</label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                          <label class="col-sm-3 control-label">返回结果</label>
                                          <div class="col-sm-6">
                                               <textarea class="form-control">{{ ret }}</textarea>
                                          </div>
                                    </div>
                                    <div class="form-group">
                                         <div class="col-sm-offset-8 col-sm-10">
                                              <button type="submit" class="btn btn-primary">推送</button>
                                         </div>
                                    </div>
                             </form>
                      </div>
                 </div>
            </div>
       </div>
       <!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/salt_key_list.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block css %}
<!-- DataTables-->
<link rel="stylesheet" href="/static/plugins/dataTables/css/dataTables.css">
{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">Salt认证</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">Key管理</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                           <table id="a1" class="table table-striped table-bordered" cellspacing="0" width="100%">
                               <tbody>
                                   <td class="info">所有salt-key列表</td>
                               </tbody>
                           </table>
                           <h3 class="h3">未允许的key</h3>
                           <table id="a2" class="table table-striped table-bordered" cellspacing="0" width="100%">
                               <tbody>
                               {% for each_pre in all_minions_pre %}
                                   <td>{{ each_pre }}</td>
                                   <td width="180"><a href="/deploy/key_accept/?node_name={{ each_pre }}" style="color:CornflowerBlue;font-weight:bold">允许</a></td>
                               {% endfor %}
                               </tbody>
                           </table>
                           <h3 class="h3">已管理的key</h3>
                           <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                               <tbody>
                               {% for each_minion in all_minions %}
                                  <tr>
                                   <td>{{ each_minion }}</td>
                                   <td width="180"><a href="/deploy/key_delete/?node_name={{ each_minion }}" style="color:CornflowerBlue;font-weight:bold">删除</a></td> 
                                  </tr>
                               {% endfor %}
                               </tbody>
                           </table>
                           <div class="row">
                                 <div class="col-xs-6">
                                       <div class="dataTables_info" id="example_info" role="alert" aria-live="polite" aria-relevant="all"></div>
                                 </div>
                                 <div class="col-xs-6">
                                      <div class="dataTables_paginate paging_simple_numbers" id="exmaple_paginate">
                                      </div>
                                 </div>
                           </div> <!--row end-->
                         </div>
                     </div>
                 </div>
             </div>
      	<!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/salt_module_by.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">智能硬件模块编译</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">智能硬件模块编译</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                             <form class="form-horizontal form-border" method="post" enctype="multipart/form-data" action=".">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">目标主机</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="tgt" value={{ tgt|capfirst }}>
                                        </div>
                                    </div>


                                 <div class="form-group">
                                        <label class="col-sm-3 control-label">版本列表</label>
                                     <div class="col-sm-6">
                                            <select name="version">
                                                {% for ver in ver_all %}
                                            <option value="{{ ver }}"> {{ ver }}</option>
                                                {% endfor %}
                                             </select>

                                         <button  onclick="window.open('{% url 'deploy:change_ver' %}')">+</button>

                                         </div>
                                         <a class="btn btn-primary" href=http://192.168.30.138:18888/hard_java/ target="_blank">编译日志</a>
                                        </div>


                                 <div class="form-group">
                                         <!--<input type="hidden" name="mod" value='bianyi'>-->
                                         <div class="col-sm-offset-8 col-sm-10">
                                              <button type="submit" class="btn btn-primary">编译</button>
                                         </div>
                                    </div>



                                    <div class="form-group">
                                          <label class="col-sm-3 control-label">返回结果</label>
                                          <div class="col-sm-6">
                                               <textarea class="form-control" rows="10">{{ ret }}</textarea>
                                          </div>

                                        <a class="btn btn-primary" href="{% url 'deploy:module_fabu' %}" target="_blank">发布链接</a>

                                    </div>


                             </form>
                      </div>
                 </div>
            </div>
       </div>
       <!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/salt_module_fabu.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">智能硬件模块发布</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">智能硬件模块发布</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                             <form class="form-horizontal form-border" method="post" enctype="multipart/form-data" action=".">

                                 <div class="form-group">
                                        <label class="col-sm-3 control-label">部署环境</label>
                                        <div class="col-sm-6">

                                            <label class="radio-inline">
                                                <input class="icheck" type="radio" name="env" value="pre" checked="checked">预发布</label>
                                            <label class="radio-inline">
                                                <input class="icheck" type="radio" name="env" value="prod">正式(暂不开放)</label>

                                        </div>

                                    </div>
                                    <div class="form-group">
                                          <label class="col-sm-3 control-label">发布模块</label>
                                          <div class="col-sm-6">
                                              <select name="fbmk">
                                                  <!--<option value="0">000</option>-->
                                                  <!--<option value="1">111</option>-->
                                                  {% for mod in module %}
                                            <option value="{{ mod }}">{{ mod }}</option>
                                                  {% endfor %}
                                             </select>


                                          </div>
                                    </div>


                                    <div class="form-group">
                                        <!--<input type="hidden" name="mod" value='fabu'>-->

                                         <div class="col-sm-offset-8 col-sm-10">
                                              <button type="submit" class="btn btn-primary">发布</button>
                                         </div>
                                    </div>


                                    <div class="form-group">
                                          <label class="col-sm-3 control-label">返回结果</label>
                                          <div class="col-sm-6">
                                               <textarea class="form-control" rows="10">{{ ret }}</textarea>
                                          </div>
                                    </div>
                             </form>
                      </div>
                 </div>
            </div>
       </div>
       <!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V6 - 用户登陆/koms/oms/templates/salt/salt_remote_execution.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>部署管理</li>
                     <li class="active">远程管理</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">命令执行</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                             <form class="form-horizontal form-border" method="post" enctype="multipart/form-data" action="{% url 'deploy:remote_execution' %}?action=exec">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">目标主机</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="tgt" value=localhost{{ tgt }}>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">远程命令</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="arg" value={{ arg }}>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                         <div class="col-sm-offset-8 col-sm-10">
                                              <button type="submit" class="btn btn-primary">提交</button>
                                         </div>
                                    </div>
                                    <div class="form-group">
                                          <label class="col-sm-3 control-label">返回结果</label>
                                          <div class="col-sm-6">
                                               <textarea style="height:400px;width:850.5px;background-color:rgb(250,250,250)">{{ ret }}</textarea>
                                          </div>
                                    </div>
                             </form>
                      </div>
                 </div>
            </div>
       </div>
       <!--row end-->

{% endblock %}