Django项目/Django1.x/原创运维平台/V5-集成故障报告/koms/oms/asset/urls.py
#coding:utf-8
from django.conf.urls import url
from .views import  *

# 命名正则表达式组的语法是(?P<name>pattern)，其中name 是组的名称，pattern 是要匹配的模式
urlpatterns = [
    url(r'^host_list/',host_list,name='host_list'),
    url(r'^add_host/',host_list_manage,name='add_host'),
    url(r'^host_delete/',host_list_manage,name='host_delete'),
    url(r'^host_manage/(?P<id>\d+)/$',host_list_manage,name='host_manage'),
    url(r'^device_list/',network_device_list,name='network_device_list'),
    url(r'^device_add/',network_device_discovery,name='add_device'),
    url(r'^idc_list/',idc_asset_list,name='idc_asset_list'),
    url(r'^add_idc/',idc_asset_manage,name='add_idc'),

]

Django项目/Django1.x/原创运维平台/V5-集成故障报告/koms/oms/oms/urls.py
#coding:utf-8
from django.conf.urls import url,include
from django.contrib import admin
from . import  views

urlpatterns = [
    url(r'^oms/admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^deploy/',include('deploy.urls', namespace="deploy")),
    url(r'^asset/',include('asset.urls', namespace="asset")),
    url(r'^installed/',include('installed.urls', namespace="installed")),
    url(r'^monitor/',include('monitor.urls', namespace="monitor")),
    url(r'^content/',include('content.urls', namespace="content")),

]

Django项目/Django1.x/原创运维平台/V5-集成故障报告/koms/oms/templates/idc/idc_list.html
{% extends "base.html" %}
{% block title %}OMS{% endblock %}
{% block css %}
<!-- DataTables-->
<link rel="stylesheet" href="/static/plugins/dataTables/css/dataTables.css">
{% endblock %}
{% block content %}
       <div class="row">
            <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                     <li><a href="{% url 'index' %}">Dashboard</a>
                     </li>
                     <li>资产管理</li>
                     <li class="active">数据中心资产</li>
               </ul>
               <!--breadcrumbs end -->
               <h1 class="h1">数据中心资产</h1>
            </div>
       </div>

       <div class="row">
            <div class="col-md-12">
                 <div class="panel panel-default">
                      <div class="panel-body">
                           {% if all_idc_list %}
                           <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                               <thead>
                                   <tr>
                                      <th>ID</th>
                                      <th>机房名称</th>
                                      <th>机房类型</th>
                                      <th>机房地址</th>
                                      <th>到期时间</th>
                                      <th>机房联系电话</th>
                                      <th>备注</th>
                                   </tr>
                               </thead>
                               
                               <tbody>
                               {% for each_idc in all_idc_list %}
                                   <tr>
                                      <td>{{ forloop.counter }}</td>
                                      <td>{{ each_idc.idc_name }}</td>
                                      <td>{{ each_idc.idc_type }}</td>
                                      <td>{{ each_idc.idc_location }}</td>
                                      <td>{{ each_idc.contract_date }}</td>
                                      <td>{{ each_idc.idc_contacts }}</td>
                                      <td>{{ each_idc.remark }}</td>
                                   </tr>
                               {% endfor %}
                               </tbody>
                            </table>
                           {% endif %}
                            <div class="row">
                                 <div class="col-xs-6">
                                       <div class="dataTables_info" id="example_info" role="alert" aria-live="polite" aria-relevant="all"></div>
                                 </div>
                                 <div class="col-xs-6">
                                      <div class="dataTables_paginate paging_simple_numbers" id="exmaple_paginate">
                                           <a href="{% url 'asset:add_idc' %}" class="btn btn-info btn-sm" role="button">添加</a>
                                      </div>
                                 </div>
                           </div> <!--row end-->
                         </div>
                     </div>
                 </div>
             </div>
      	<!--row end-->

{% endblock %}

Django项目/Django1.x/原创运维平台/V5-集成故障报告/koms/oms/templates/idc/idc_manage.html
{% extends "base.html" %}
{% block content %}
                <div class="row">
                    <div class="col-md-12">
                        <!--breadcrumbs start -->
                        <ul class="breadcrumb">
                            <li><a href="{% url 'index' %}">Dashboard</a>
                            </li>
                            <li>资产管理</li>
                            <li class="active">{{ page_name }}</li>
                        </ul>
                        <!--breadcrumbs end -->
                        <h1 class="h1">{{ page_name }}</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <form class="form-horizontal form-border" id="form" method="post" action=".">
                                       {% csrf_token %}
                                       <div class="form-group">
                                             <label class="col-sm-3 control-label">机房名称</label>
                                             <div class="col-sm-6">
                                             {{ form.idc_name }}
                                             {{ form.idc_name.errors }}
                                             </div>
                                       </div>
                                       <div class="form-group">
                                             <label class="col-sm-3 control-label">机房类型</label>
                                             <div class="col-sm-6">
                                             {{ form.idc_type }}
                                             {{ form.idc_type.errors }}
                                             </div>
                                        </div>
                                        <div class="form-group">
                                             <label class="col-sm-3 control-label">机房位置</label>
                                             <div class="col-sm-6">
                                             {{ form.idc_location }}
                                             {{ form.idc_location.errors }}
                                             </div>
                                        </div>
                                        <div class="form-group">
                                             <label class="col-sm-3 control-label">到期时间</label>
                                             <div class="col-sm-6">
                                             {{ form.contract_date }}
					     {{ form.contract_date.errors }}
                                             </div>
                                        </div>
                                        <div class="form-group">
                                             <label class="col-sm-3 control-label">机房联系电话</label>
                                             <div class="col-sm-6">
                                             {{ form.idc_contacts }}
                                             {{ form.idc_contacts.errors }}
                                             </div>
                                        </div>
                                        <div class="form-group">
                                             <label class="col-sm-3 control-label">备注</label>
                                             <div class="col-sm-6">
                                             {{ form.remark }}
					     {{ form.remark.errors }}
                                              </div>
                                         </div> 
                                         <div class="col-sm-offset-8 col-sm-10">
                                             {% ifequal action 'add' %}
                                             <button type="submit" class="btn btn-primary">添加</button>
                                             {% endifequal %}
                                             {% ifequal action 'edit' %}
                                             <button type="submit" class="btn btn-primary" name="operate" value="update">更新</button>
                                             {% endifequal %}
                                        </div>
                                    </div>
                                </form>

                            </div> <!-- panel body -->
                        </div> <!-- panel end -->
                    </div> <!-- col end -->
                </div> <!-- row end -->

{% endblock %}